<%@ Page Language="C#" MasterPageFile="Admin.master" ValidateRequest="false" AutoEventWireup="true"
    CodeFile="ManageDepartments.aspx.cs" Inherits="UC.UI.Admin.ManageDepartments"
    Culture="auto" UICulture="auto" %>

<%@ Register Src="~/Admin/Controls/DepartmentDescriptionControl.ascx" TagName="DepartmentDescriptionControl"
    TagPrefix="mb" %>
<%@ Register Src="~/Admin/Controls/DepartmentFiltersControl.ascx" TagName="DepartmentFiltersControl"
    TagPrefix="mb" %>
<%@ Register Src="~/Admin/Controls/DepartmentLongDescriptionControl.ascx" TagName="DepartmentLongDescriptionControl"
    TagPrefix="mb" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="Server">
    <div class="breadcrumb">
        <table>
            <tr>
                <td class="h1">
                    <a href="../Default.aspx">Главная</a>
                </td>
                <td>
                    <asp:Image ID="Image1" runat="server" SkinID="Separator" />
                </td>
                <td class="h1">
                    <a href="Default.aspx">Администрирование</a>
                </td>
                <td>
                    <asp:Image ID="Image2" runat="server" SkinID="Separator" />
                </td>
                <td>
                    <h1>
                        Управление разделами</h1>
                </td>
            </tr>
        </table>
    </div>
    <div id="content">
        <p>
        </p>
        <asp:UpdatePanel ID="updpnlManageDepartment" runat="server">
            <ContentTemplate>
                <table width="100%">
                    <tr>
                        <td>
                            <asp:TreeView ID="tvwDepartments" runat="server" AutoGenerateDataBindings="False"
                                ExpandDepth="0" DataSourceID="ds" OnSelectedNodeChanged="tvwDepartments_SelectedNodeChanged"
                                OnUnload="tvwDepartments_Unload">
                                <DataBindings>
                                    <asp:TreeNodeBinding TextField="title" ValueField="departmentID" />
                                </DataBindings>
                            </asp:TreeView>
                            <asp:XmlDataSource ID="ds" EnableCaching="false" runat="server" XPath="/*/*"></asp:XmlDataSource>
                        </td>
                        <td style="width: 100%">
                            <ajaxToolkit:TabContainer runat="server" ID="DepartmentTabs" ActiveTabIndex="0" Width="100%">
                                <ajaxToolkit:TabPanel runat="server" ID="pnlDepartmentDescription" HeaderText="Описание раздела"
                                    Width="100%">
                                    <ContentTemplate>
                                        <mb:DepartmentDescriptionControl ID="DepartmentDescription" runat="server" OnItemInserted="UpdateTree"
                                            OnItemUpdated="UpdateTree" OnItemDeleted="UpdateTree" OnItemCancel="UpdateTree" />
                                    </ContentTemplate>
                                </ajaxToolkit:TabPanel>
                                <ajaxToolkit:TabPanel runat="server" ID="pnlDepartmentFilter" HeaderText="Фильтры"
                                    Width="100%">
                                    <ContentTemplate>
                                        <mb:DepartmentFiltersControl ID="DepartmentFiltersControl" runat="server" />
                                    </ContentTemplate>
                                </ajaxToolkit:TabPanel>
                                <ajaxToolkit:TabPanel runat="server" ID="pnlDepartmentLongDescription" HeaderText="Расширенное описание"
                                    Width="100%">
                                    <ContentTemplate>
                                        <mb:DepartmentLongDescriptionControl ID="DepartmentLongDescriptionControl" runat="server" />
                                    </ContentTemplate>
                                </ajaxToolkit:TabPanel>
                            </ajaxToolkit:TabContainer>
                        </td>
                    </tr>
                </table>
            </ContentTemplate>
        </asp:UpdatePanel>
    </div>
</asp:Content>
