<%@ Page Language="C#" ValidateRequest="false" MasterPageFile="Admin.master" AutoEventWireup="true" CodeFile="AddEditArticle.aspx.cs" Inherits="UC.UI.Admin.AddEditArticle" Culture="auto" UICulture="auto" %>
<%@ Register Src="../Controls/FileUploader.ascx" TagName="FileUploader" TagPrefix="mb" %>
<%@ Register Src="../Controls/RatingDisplay.ascx" TagName="RatingDisplay" TagPrefix="mb" %>
<%@ Register Src="~/Admin/Controls/ImageUploader.ascx" TagName="ImageUploader" TagPrefix="mb" %>
<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>

<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" Runat="Server">
    <div class="breadcrumb">
        <table>
            <tr>
                <td class="h1">
                    <a href="../Default.aspx">Главная</a>
                </td>
                <td>
                    <asp:Image ID="Image1" runat="server" SkinID="Separator" />
                </td>
                <td class="h1">
                    <a href="Default.aspx">Администрирование</a>
                </td>
                <td>
                    <asp:Image ID="Image3" runat="server" SkinID="Separator" />
                </td>
                <td class="h1">
                    <a href="ManageArticles.aspx">Управление статьями</a>
                </td>
                <td>
                    <asp:Image ID="Image2" runat="server" SkinID="Separator" />
                </td>
                <td>
                    <h1>Добавление статьи</h1>
                </td>
            </tr>
        </table>
    </div>
    <div id="content">
   <div class="sectiontitle">
      <asp:Literal runat="server" ID="lblNewArticle" Text="Добавить новую статью"/>
      <asp:Literal runat="server" ID="lblEditArticle" Text="Редактировать статью" Visible="False"/>
   </div>
   <p></p>
   <asp:DetailsView ID="dvwArticle" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
      AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="ID" DataSourceID="objCurrArticle"
      DefaultMode="Insert" HeaderText="Детали статьи" OnItemCreated="dvwArticle_ItemCreated" OnDataBound="dvwArticle_DataBound" OnModeChanged="dvwArticle_ModeChanged" meta:resourcekey="dvwArticleResource1" OnItemUpdated="dvwArticle_ItemUpdated">
      <FieldHeaderStyle Width="117px" />
      <Fields>
         <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID"/>
         <asp:BoundField DataField="AddedDate" HeaderText="Дата добавления" InsertVisible="False" ReadOnly="True" SortExpression="AddedDate" DataFormatString="{0:f}"/>
         <asp:BoundField DataField="AddedBy" HeaderText="Добавил" InsertVisible="False" ReadOnly="True" SortExpression="AddedBy"/>
         <asp:BoundField DataField="ViewCount" HeaderText="Прочитана" InsertVisible="False" ReadOnly="True" SortExpression="ViewCount"/>
         <asp:BoundField DataField="Votes" HeaderText="Голосов" InsertVisible="False" ReadOnly="True" SortExpression="Votes"/>
         <asp:BoundField DataField="AverageRating" HeaderText="Рэйтинг" InsertVisible="False" DataFormatString="{0:N2}" ReadOnly="True" SortExpression="AverageRating"/>
         <asp:TemplateField HeaderText="Тема" SortExpression="CategoryID">
            <ItemTemplate>
               <asp:Label ID="lblCategory" runat="server" Text='<%# Eval("CategoryTitle") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:DropDownList ID="ddlCategories" runat="server" DataSourceID="objAllCategories"
                  DataTextField="Title" DataValueField="ID" SelectedValue='<%# Bind("CategoryID") %>' Width="100%"/>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Название" SortExpression="Title">
            <ItemTemplate>
               <asp:Label ID="lblTitle" runat="server" Text='<%# Eval("Title") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:TextBox ID="txtTitle" runat="server" Text='<%# Bind("Title") %>' Width="100%" MaxLength="256"></asp:TextBox>
               <asp:RequiredFieldValidator ID="valRequireTitle" runat="server" ControlToValidate="txtTitle" SetFocusOnError="True" Display="Dynamic">обязательно для заполнения</asp:RequiredFieldValidator>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Краткое описание" SortExpression="Abstract">
            <ItemTemplate>
               <asp:Label ID="lblAbstract" runat="server" Text='<%# Eval("Abstract") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:TextBox ID="txtAbstract" runat="server" Text='<%# Bind("Abstract") %>' Rows="5" TextMode="MultiLine" Width="100%" MaxLength="4000"></asp:TextBox>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Текст" SortExpression="Body">
            <ItemTemplate>
               <asp:Label ID="lblBody" runat="server" Text='<%# Eval("Body") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <fckeditorv2:fckeditor id="txtBody" runat="server" Value='<%# Bind("Body") %>' Height="400px" Width="100%" />
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Отображать с" SortExpression="ReleaseDate">
            <ItemTemplate>
               <asp:Label ID="lblReleaseDate" runat="server" Text='<%# Eval("ReleaseDate", "{0:d}") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:TextBox ID="txtReleaseDate" runat="server" Text='<%# Bind("ReleaseDate", "{0:d}") %>' Width="100%"></asp:TextBox>
               <asp:CompareValidator runat="server" ID="valReleaseDateType" ControlToValidate="txtReleaseDate"
                  SetFocusOnError="True" Display="Dynamic" Operator="DataTypeCheck" Type="Date">неправильный формат даты</asp:CompareValidator>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Отображать до" SortExpression="ExpireDate">
            <ItemTemplate>
               <asp:Label ID="lblExpireDate" runat="server" Text='<%# Eval("ExpireDate", "{0:d}") %>'></asp:Label>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:TextBox ID="txtExpireDate" runat="server" Text='<%# Bind("ExpireDate", "{0:d}") %>' Width="100%"></asp:TextBox>
               <asp:CompareValidator runat="server" ID="valExpireDateType" ControlToValidate="txtExpireDate"
                  SetFocusOnError="True" Display="Dynamic" Operator="DataTypeCheck" Type="Date">неправильный формат даты</asp:CompareValidator>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Утверждена" SortExpression="Approved">
            <ItemTemplate>
               <asp:CheckBox ID="chkApproved" runat="server" Checked='<%# Eval("Approved") %>' Enabled="False"/>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:CheckBox ID="chkApproved" runat="server" Checked='<%# Bind("Approved") %>'/>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Отображать в общем списке" SortExpression="Listed">
            <ItemTemplate>
               <asp:CheckBox ID="chkListed" runat="server" Checked='<%# Eval("Listed") %>' Enabled="False"/>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:CheckBox ID="chkListed" runat="server" Checked='<%# Bind("Listed") %>'/>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Добавление комментариев" SortExpression="CommentsEnabled">
            <ItemTemplate>
               <asp:CheckBox ID="chkCommentsEnabled" runat="server" Checked='<%# Eval("CommentsEnabled") %>' Enabled="False"/>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:CheckBox ID="chkCommentsEnabled" runat="server" Checked='<%# Bind("CommentsEnabled") %>'/>
            </EditItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="Только для зарегистрированных пользователей" SortExpression="OnlyForMembers">
            <ItemTemplate>
               <asp:CheckBox ID="chkOnlyForMembers" runat="server" Checked='<%# Eval("OnlyForMembers") %>' Enabled="False"/>
            </ItemTemplate>
            <EditItemTemplate>
               <asp:CheckBox ID="chkOnlyForMembers" runat="server" Checked='<%# Bind("OnlyForMembers") %>'/>
            </EditItemTemplate>
         </asp:TemplateField>         
      </Fields>
   </asp:DetailsView>
   <asp:ObjectDataSource ID="objCurrArticle" runat="server" DeleteMethod="DeleteArticle"
      InsertMethod="InsertArticle" SelectMethod="GetArticleByID" TypeName="UC.BLL.Articles.Article"
      UpdateMethod="UpdateArticle" OnInserted="objCurrArticle_Inserted">
      <DeleteParameters>
         <asp:Parameter Name="id" Type="Int32" />
      </DeleteParameters>
      <UpdateParameters>
         <asp:Parameter Name="id" Type="Int32" />
         <asp:Parameter Name="categoryID" Type="Int32" />
         <asp:Parameter Name="title" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="Abstract" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="body" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="releaseDate" Type="DateTime" />
         <asp:Parameter Name="expireDate" Type="DateTime" />
         <asp:Parameter Name="approved" Type="Boolean" />
         <asp:Parameter Name="listed" Type="Boolean" />
         <asp:Parameter Name="commentsEnabled" Type="Boolean" />
         <asp:Parameter Name="onlyForMembers" Type="Boolean" />
      </UpdateParameters>
      <SelectParameters>
         <asp:QueryStringParameter Name="articleID" QueryStringField="ID" Type="Int32" />
      </SelectParameters>
      <InsertParameters>
         <asp:Parameter Name="categoryID" Type="Int32" />
         <asp:Parameter Name="title" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="Abstract" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="body" Type="String" ConvertEmptyStringToNull="False" />
         <asp:Parameter Name="releaseDate" Type="DateTime" />
         <asp:Parameter Name="expireDate" Type="DateTime" />
         <asp:Parameter Name="approved" Type="Boolean" />
         <asp:Parameter Name="listed" Type="Boolean" />
         <asp:Parameter Name="commentsEnabled" Type="Boolean" />
         <asp:Parameter Name="onlyForMembers" Type="Boolean" />
      </InsertParameters>
   </asp:ObjectDataSource>   
   <asp:ObjectDataSource ID="objAllCategories" runat="server" SelectMethod="GetCategories"
      TypeName="UC.BLL.Articles.Category"></asp:ObjectDataSource>
   <asp:ObjectDataSource ID="objAllCountries" runat="server" SelectMethod="GetCountries"
      TypeName="UC.Helpers">
      <SelectParameters>
         <asp:Parameter DefaultValue="true" Name="insertEmpty" Type="Boolean" />
      </SelectParameters>
   </asp:ObjectDataSource>
   <mb:ImageUploader runat="server" ID="imageUploader" AbsoluteUrl="Images\\Articles\\" Url="Images/Articles/" />
   </div>
</asp:Content>

