<%@ Page Language="C#" ValidateRequest="false" MasterPageFile="Admin.master" AutoEventWireup="true"
    CodeFile="AddEditNewsletter.aspx.cs" Inherits="UC.UI.Admin.AddEditNewsletter" %>

<%@ Register Assembly="FredCK.FCKeditorV2" Namespace="FredCK.FCKeditorV2" TagPrefix="FCKeditorV2" %>
<%@ Register Src="~/Admin/Controls/ImageUploader.ascx" TagName="ImageUploader" TagPrefix="mb" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="Server">
    <div class="breadcrumb">
        <table>
            <tr>
                <td class="h1">
                    <a href="../Default.aspx">Главная</a>
                </td>
                <td>
                    <asp:Image ID="Image1" runat="server" SkinID="Separator" />
                </td>
                <td class="h1">
                    <a href="Default.aspx">Администрирование</a>
                </td>
                <td>
                    <asp:Image ID="Image3" runat="server" SkinID="Separator" />
                </td>
                <td class="h1">
                    <a href="ManageNewsletters.aspx">Управление новостями</a>
                </td>
                <td>
                    <asp:Image ID="Image2" runat="server" SkinID="Separator" />
                </td>
                <td>
                    <h1>
                        Добавление новости</h1>
                </td>
            </tr>
        </table>
    </div>
    <div id="content">
        <asp:Label runat="server" ID="lblTitle" CssClass="labeltitle" Font-Size="14px" /><br />
        <br />
        <asp:DetailsView ID="dvwNewsletter" HeaderText="Описание новости" runat="server"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True"
            AutoGenerateRows="False" DataKeyNames="ID" DataSourceID="objCurrNewsletter" DefaultMode="Insert"
            OnItemCreated="dvwNewsletter_ItemCreated" OnModeChanged="dvwNewsletter_ModeChanged"
            OnItemUpdated="dvwNewsletter_ItemUpdated" OnDataBound="dvwNewsletter_DataBound">
            <FieldHeaderStyle Width="100px" />
            <Fields>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True"
                    SortExpression="ID" />
                <%--<asp:BoundField DataField="AddedDate" HeaderText="Дата добавления" InsertVisible="False"
                    ReadOnly="True" SortExpression="AddedDate" DataFormatString="{0:f}" />--%>
                <asp:BoundField DataField="AddedBy" HeaderText="Добавил" InsertVisible="False" ReadOnly="True"
                    SortExpression="AddedBy" />
                <asp:TemplateField HeaderText="Заголовок" SortExpression="Title">
                    <ItemTemplate>
                        <asp:Label ID="lblTitle" runat="server" Text='<%# Eval("Subject") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtTitle" runat="server" Text='<%# Bind("subject") %>' Width="100%"
                            MaxLength="256"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="valRequireTitle" runat="server" ControlToValidate="txtTitle"
                            SetFocusOnError="True" Display="Dynamic">* обязательно для заполнения</asp:RequiredFieldValidator>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Дата публикации" SortExpression="AddedDate">
                    <ItemTemplate>
                        <asp:Label ID="lblTitle" runat="server" Text='<%# Eval("AddedDate") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtStartDate" Text='<%# Bind("AddedDate") %>' />
                        <asp:ImageButton runat="Server" ID="iStartDate" ImageUrl="~/images/Calendar_scheduleHS.png"
                            AlternateText="Нажмите для отображения календаря" /><br />
                        <ajaxToolkit:CalendarExtender ID="cStartDateButtonExtender" runat="server" TargetControlID="txtStartDate"
                            PopupButtonID="iStartDate" Format="dd.MM.yyyy" SelectedDate='<%# Eval("AddedDate") %>'/>
                        <asp:RegularExpressionValidator ID="AddedDate" runat="server" EnableClientScript="False"
                            Display="Dynamic" ControlToValidate="txtStartDate" ValidationExpression="(\d+).(\d+).((\d{4}))">* неверный фомат даты</asp:RegularExpressionValidator>
                    </EditItemTemplate>
                </asp:TemplateField>                
                <asp:TemplateField HeaderText="Краткое описание" SortExpression="Abstract">
                    <ItemTemplate>
                        <asp:Label ID="lblAbstract" runat="server" Text='<%# Eval("Abstract") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtAbstract" runat="server" Text='<%# Bind("Abstract") %>' Rows="5"
                            TextMode="MultiLine" Width="100%" MaxLength="4000"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Текст новости" SortExpression="HtmlBody">
                    <ItemTemplate>
                        <asp:Label ID="lblBody" runat="server" Text='<%# Eval("HtmlBody") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <FCKeditorV2:FCKeditor ID="txtBody" runat="server" Height="400px" Width="100%" Value='<%# Bind("HtmlBody") %>'></FCKeditorV2:FCKeditor>                    
                    </EditItemTemplate>
                </asp:TemplateField>
            </Fields>
        </asp:DetailsView>
        <asp:ObjectDataSource ID="objCurrNewsletter" runat="server" DeleteMethod="DeleteNewsletter"
            InsertMethod="InsertNewsletter" SelectMethod="GetNewsletterByID" TypeName="UC.BLL.Newsletters.Newsletter"
            UpdateMethod="UpdateNewsletter" OnInserted="objCurrNewsletter_Inserted">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="id" Type="Int32" />
                <asp:Parameter Name="AddedDate" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="subject" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="Abstract" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="htmlBody" Type="String" ConvertEmptyStringToNull="False" />
            </UpdateParameters>
            <SelectParameters>
                <asp:QueryStringParameter Name="newsletterID" QueryStringField="ID" Type="Int32" />
            </SelectParameters>
            <InsertParameters>
                <asp:Parameter Name="AddedDate" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="subject" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="Abstract" Type="String" ConvertEmptyStringToNull="False" />
                <asp:Parameter Name="htmlbody" Type="String" ConvertEmptyStringToNull="False" />
            </InsertParameters>
        </asp:ObjectDataSource>
        
                        <asp:UpdatePanel ID="updpnlProductSpecification" runat="server">
                            <ContentTemplate>        
        <mb:ImageUploader runat="server" ID="imageUploader" AbsoluteUrl="Images\\News\\"
            Url="Images/News/" />
                            </ContentTemplate>
                        </asp:UpdatePanel>            
    </div>
</asp:Content>
